Repository hitobito/hitobito, pull requests merged in 2024-10, with the labels that each got.

#2919 Prevent XSS in email URLs
  app/mailers/application_mailer.rb
  spec/mailers/application_mailer_spec.rb
Labels: security

#2929 Rework database config
  .github/actions/core-ci-setup/action.yml
  .github/workflows/tests.yml
  .github/workflows/wagon-tests.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  config/database.yml
Labels: tech

#2925 Migrate type of former FutureRole entries as well
  db/migrate/20240816141100_migrate_role_timestamps_and_future_roles.rb
  db/migrate/20240816141100_set_roles_start_end_from_timestamps.rb
Labels: core, interest-sac
