Repository hitobito/hitobito, pull requests merged in 2024-11, with the labels that each got.

#3006 Rewrite migration in plain sql to not confuse validates_by_schema
  db/migrate/20240812093000_add_disclosure_to_event_questions.rb
Labels: bug

#2822 fix: load role_type from sti_class
  app/controllers/event/participation_lists_controller.rb
  app/controllers/events_controller.rb
  app/models/event/participation.rb
  app/views/event/participation_lists/_new.html.haml
  config/locales/views.de.yml
  spec/controllers/event/participation_lists_controller_spec.rb
Labels: interest-pbs, Mergefreeze

#3026 Simplify mailing list subscribe/unsubscribe person
  app/controllers/subscriber/exclude_person_controller.rb
  app/domain/person/subscriptions.rb
  app/models/mailing_list.rb
  spec/domain/person/subscriptions_spec.rb
Labels: High Prio!, SAC-MVP
