Repository hitobito/hitobito, pull requests merged in 2025-07, with the labels that each got.

#3431 Restore: quote strings for inserts
  lib/tasks/restore.rake
Labels: run-wagon-tests!

#3506 Escape query when replacing string to not display encodings in quicksearch
  app/javascript/javascripts/modules/remote_autocomplete.js
Labels: run-wagon-tests!

#3510 Ignore exceptions caused by attempted drupal exploits
  config/initializers/sentry.rb
Labels: error

#3539 Handle both arrays and hashes for the param
  app/controllers/events_controller.rb
Labels: error, run-wagon-tests!

#3528 Add feature toggle for custom dashboard page (hitobito/hitobito_insieme#150)
  app/controllers/dashboard_controller.rb
  app/views/dashboard/dashboard.html.haml
  config/routes.rb
  config/settings.yml
  db/seeds/custom_contents.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/features/dashboard_spec.rb
Labels: run-wagon-tests!

#3546 Improve message dispatch
  app/domain/invoice/batch_create.rb
  app/domain/invoice/batch_update.rb
  app/domain/messages/letter_dispatch.rb
  app/domain/messages/letter_with_invoice_dispatch.rb
  app/jobs/messages/dispatch_job.rb
  doc/developer/messages/dispatch.md
Labels: run-wagon-tests!

#3468 Add tests for nil primary_group
  spec/domain/table_displays/people/primary_group_column_spec.rb
Labels: run-wagon-tests!

#3552 Allow normalizing labels of archived roles
  app/models/role.rb
  spec/models/role_spec.rb
Labels: run-wagon-tests!
